### ISSUE TITLE
Issue with clear screen

### ISSUE THREAD

**Issue by rteicheira** [ar51an/raspberrypi-motd#12]
I am not sure if this is system with mine, but I had it with both my brand new Pi5 with the latest OSes and patches (I didn't try it on my old Pi 3+ before I wiped it). 

The clear you have in "10-welcome" for some reason isn't working, even though it looks like it should.

I fixed it by creating a "00-header" that runs "/etc/motd.clean" with "^[[H^[[" (in nano, ALT + V, ALT + [, SHIFT + H, ALT + V, ALT + [) the only line in the file, to get it to clear the screen before the MOTD.

**Comment by ar51an** [comment]
There is no `clear` cmd in the latest version. Even in the old version the clear cmd was added as a precautionary measure during development and thus removed as part of cleanup in latest version. If you were expecting that `clear` cmd will clear the first two lines about username and authentication, it won't. That was never the intention.

![motd-issue](https://github.com/user-attachments/assets/2e7d0461-4d68-44b9-abea-88ad89d7e742)

If you have removed the old motd as mentioned in the instructions in `Readme`, nothing is there apart from those two authentication lines. This is how motd works in Debian and Ubuntu as well along with those authentication lines.
