### ISSUE TITLE
/etc/update-motd-static.d/20-update: línea 11: [: ==: se esperaba un operador unario

### ISSUE THREAD

**Issue by jddmarand** [ar51an/raspberrypi-motd#6]

**Comment by ar51an** [comment]
English? What is the issue?

**Comment by hardrockhodl** [comment]
/etc/update-motd-static.d//20-update: line 11: [: ==: unary operator was expected

line1: #!/bin/bash
line2: 
line3: function color (){
line4:   echo "\e[$1m$2\e[0m"
line5: }
line6: 
line7: function setCountColor (){
line8:   local input=$1
line9:   countColor="38;5;16;48;5;242"
line10: 

> line11:   if [ $input == 0 ]; then

line12:     countColor="38;5;16;48;5;242"
line13:   else
line14:     countColor="38;5;16;48;5;71"
line15:   fi
line16: }
