### ISSUE TITLE
strange character in update.sh

### ISSUE THREAD

**Issue by BenRoe** [ar51an/raspberrypi-motd#7]
Hello,
everything works, but i get some strange character in the headline of the update.sh script.

<img width="568" alt="Bildschirmfoto 2023-09-13 um 22 14 41" src="https://github.com/ar51an/raspberrypi-motd/assets/643834/a28ff74e-3d26-41e1-8e9b-ebe65e107323">

If i open the update.sh script here on [GitHub in raw](https://raw.githubusercontent.com/ar51an/raspberrypi-motd/main/update-os/update.sh), it shows the same character.

<img width="583" alt="Bildschirmfoto 2023-09-13 um 22 18 51" src="https://github.com/ar51an/raspberrypi-motd/assets/643834/e3405936-a24a-4e41-b0f9-4cd1cfc13407">

but in normal code view it's fine.

<img width="583" alt="Bildschirmfoto 2023-09-13 um 22 18 30" src="https://github.com/ar51an/raspberrypi-motd/assets/643834/685086a0-a035-446e-81ad-4d4e70860bc2">

Any idea what this could cause?

**Comment by ar51an** [comment]
These are unicode right and left arrows.
[Right Arrow](https://www.compart.com/en/unicode/U+2B9E)
[Left Arrow](https://www.compart.com/en/unicode/U+2B9C)

This is the screenshot of update.sh in [Raw](https://raw.githubusercontent.com/ar51an/raspberrypi-motd/main/update-os/update.sh):

![image](https://github.com/ar51an/raspberrypi-motd/assets/11185794/44b0560c-2cf6-4771-ac00-72868cc817ec)

This is the screenshot when update.sh is executed in shell:

![image](https://github.com/ar51an/raspberrypi-motd/assets/11185794/61c2b127-a07a-4761-8521-cee4d2f0f95d)

I mentioned under [putty](https://github.com/ar51an/raspberrypi-motd/tree/main/putty) section in the last screenshot. Make sure whatever client you use it has UTF-8 enabled.

**Comment by BenRoe** [comment]
Ok thank you for the hint.
Are you viewing the raw on windows? I am on Mac and it does not show correct.
To make it easier for newbies, replacing these Unicode characters with some standard character like `>>` `<<` would help.
Or if you want some fancy symbols, [Nerdfonts](https://www.nerdfonts.com) is also great.
Only a suggestion.

**Comment by ar51an** [comment]
Yes the github raw screenshot is from win machine but it looks the same in debian and ubuntu as well. Unicode is pretty much the standard across windows, unix and mac-os.

You can try copy/pasting the arrow into a document or display it in character viewer to see if the default font you are using has it. If you are able to view it using one of the these methods than it is the browser that is not able to render it. Firefox renders unicode charcters much better than Safari or Chrome.

The arrows I used above are basic UTF-8 arrows that are available across majority of the fonts in win and unix. They are also renderable in github which supports restricted unicode character set. You can check [here](https://www.htmlsymbols.xyz/unicode/U+2B9E) various mac fonts have these arrows

I do not want to use any fancy characters, most of them require specific font to be installed. Anyways I will remove them in future release, they are not adding any value to the functionality.

**Comment by ar51an** [comment]
Removed unicode arrows from update.sh
[Commit](https://github.com/ar51an/raspberrypi-motd/commit/c3afcb8c752058da0b5d77cbe721b8d7f2c5ea4f)
